# Generated by Django 2.2.7 on 2019-11-06 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchbets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchmarket',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matchmarket',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='matchbets.Match'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='selection',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='matchbets.MatchMarket'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
