# Generated by Django 2.2.7 on 2019-11-06 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchbets', '0002_auto_20191106_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('NewEvent', 'New Event'), ('UpdateOdds', 'Update Odds')], max_length=1024)),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matchbets.Match')),
            ],
        ),
    ]
